stages:
  - deploy

deploy:
  image: maven:3.9.2-eclipse-temurin-17
  stage: deploy
  services:
    - postgres:latest
    - name: docker:dind
      command: [ "--tls=false" ]
  cache:
    paths:
      - .m2/repository
  variables:
    MAVEN_CLI_OPTS: >-
      --batch-mode
      --errors
      --fail-at-end
      --show-version
      --no-transfer-progress
    POSTGRES_DB: customer
    POSTGRES_USER: german
    POSTGRES_PASSWORD: password
    SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/customer"
    DOCKER_HOST: "tcp://docker:2375"
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
    BUILD_NUMBER: ""
  script:
    - BUILD_NUMBER=`(date '+%d.%m.%Y.%H.%M.%S')`
    - echo $BUILD_NUMBER
    - cd ./backend
    - 'mvn $MAVEN_CLI_OPTS verify -Ddocker.image.tag=$BUILD_NUMBER jib:build -Djib.to.auth.username=$DOCKERHUB_USERNAME -Djib.to.auth.password=$DOCKERHUB_PASSWORD'
    - echo "Dockerrun.aws.json before updating tag"
    - cat Dockerrun.aws.json
    - sed -i -E 's_(ggranadosio/customer-api:)([^"]*)_\1'$BUILD_NUMBER'_' Dockerrun.aws.json
    - echo "Dockerrun.aws.json after updating tag"
    - cat Dockerrun.aws.json