services:
  db:
    container_name: postgres-spring
    image: postgres:15.4
    environment:
      POSTGRES_USER: german
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
  customer-api:
    container_name: customer-api
    image: ggranadosio/customer-api
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/customer"
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
#    command:
#      - --spring.datasource.url=jdbc:postgresql://db:5432/customer
  customer-react:
    container_name: customer-react
    image: ggranadosio/customer-react
    build:
      context: frontend/react
      args:
        api_base_url: http://localhost:8088
    ports:
      - "3000:5173"
    depends_on:
      - customer-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: